### ISSUE TITLE
Déploiement Heroku

### ISSUE THREAD

**Issue by hugo-clems** [M2DL/2019-ivvq-magnetrade#40]

**Comment by erikmd** [comment]
Liens utiles :
* https://github.com/SonarSource/sonar-scanner-cli
* https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner
* https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
